Drive SDK
deta/deta-go pull request #24
Opened 2021-07-07 15:34 UTC by rohanshiva

2021-07-07 16:06 UTC, aavshr commented on client.go
> +	if i.ShouldReadBody && res.StatusCode >= 200 && res.StatusCode <= 299 {
shouldn't be called `ShouldReadBody` if you are not reading the body when `ShouldReadBody` is `true`, can be called `SkipReadBody` ?

2021-07-07 16:07 UTC, aavshr commented on client.go
> +	if i.ShouldReadBody && res.StatusCode >= 200 && res.StatusCode <= 299 {
can also be called `ReturnReadCloser` probably better

2021-07-07 16:09 UTC, aavshr commented on drive.go
> +	uploadId, _ := d.startUpload(i.Name)
we should not ignore the error

2021-07-07 16:10 UTC, aavshr commented on drive.go
> +				return i.Name, err
return the name only on successful `put` otherwise return `""`

2021-07-07 16:11 UTC, aavshr commented on drive.go
> +// List is paginated, returns the last name fetched, and the size if further pages are left.
only `last` determines if further pages left, `size` is always returned

2021-07-07 16:14 UTC, aavshr commented on drive_test.go
> +	rootEndpoint := os.Getenv("DETA_SDK_TEST_ENDPOINT")
should be `DETA_SDK_TEST_DRIVE_ENDPOINT`

2021-07-07 16:16 UTC, aavshr commented on drive_test.go
> +	testCases := []struct {
can you please also put test cases with
1. empty content type
2. other io.Readers besides `strings.NewReader`

2021-07-07 16:24 UTC, aavshr requested changes
thanks @rohanshiva , left come comments. Also additionally, 
1. If we are returning an `error`, we generally should return an empty value for the other return value
2. `reflect.DeepEqual` can have some pitfalls sometimes, please make sure to check if it's being used correctly.

2021-07-07 16:25 UTC, rohanshiva commented
Thanks @aavshr, I will check those.

2021-07-07 16:25 UTC, aavshr commented on drive_test.go
> +import (
missing import "os"

2021-07-12 13:24 UTC, aavshr commented on drive_test.go
> +	"crypto/rand"
`math/rand` is better, we don't need crypto, crypto rand read is slower

2021-07-12 13:27 UTC, aavshr approved these changes
thanks @rohanshiva , approved, one last small thing with using `math/rand` instead of `crypto/rand`
and the test failing. 

Can you please check them out?

2021-07-12 13:44 UTC, rohanshiva commented
thanks @aavshr, changed to `math/rand` and the tests run successfully.

2021-07-12 16:17 UTC, merged